import type { PageServerLoad } from "./$types";
import { readdir, readFile, access } from "fs/promises";
import { join, parse } from "path";
import { extractPhotoMeta } from "../../../scripts/photo-exif.mjs";
import type { PhotoMeta } from "../../../scripts/photo-exif.mjs";

interface PhotoData {
    src: string;           // Original full-size path for lightbox
    thumbSrc: string;      // Optimized thumbnail for grid (default width)
    thumbSrcset?: string;  // Responsive candidate set for the grid <img>
    alt: string;
    filename: string;
    orientation: "landscape" | "portrait" | "square";
    width?: number;
    height?: number;
    exif: {
        camera?: string;
        lens?: string;
        aperture?: string;
        shutter?: string;
        iso?: string;
        date?: string;
        focalLength?: string;
    };
}

export const load: PageServerLoad = async () => {
    const photosDir = join(process.cwd(), "static", "images", "photography");

    try {
        const files = await readdir(photosDir);
        const imageFiles = files.filter((file) =>
            /\.(jpg|jpeg|png|webp)$/i.test(file)
        );

        // EXIF/dimension cache written by scripts/optimize-photos.mjs (which
        // `npm run build` runs first), so prerendering doesn't re-read every
        // full-size photo. Missing or stale-in-dev cache just means we fall
        // back to extracting from the file below.
        let metaCache: Record<string, PhotoMeta> = {};
        try {
            metaCache = JSON.parse(
                await readFile(join(photosDir, "thumbs", "photo-meta.json"), "utf-8")
            );
        } catch {
            // no cache yet (fresh checkout / dev server)
        }

        const photos: PhotoData[] = await Promise.all(
            imageFiles.map(async (filename) => {
                const filePath = join(photosDir, filename);

                const meta: PhotoMeta =
                    metaCache[filename] ??
                    extractPhotoMeta(await readFile(filePath), filename);
                const { exif, orientation, width, height } = meta;

                // Generate alt text from filename
                const alt = filename
                    .replace(/\.[^.]+$/, "") // Remove extension
                    .replace(/[-_]/g, " ") // Replace dashes/underscores with spaces
                    .replace(/\b\w/g, (c) => c.toUpperCase()); // Capitalize words

                // Check for optimized thumbnail
                const { name } = parse(filename);
                const thumbsBase = `/images/photography/thumbs`;
                const thumbPath = join(photosDir, "thumbs", `${name}.webp`);
                let thumbSrc = `/images/photography/${filename}`; // Default to original
                let thumbSrcset: string | undefined;

                try {
                    await access(thumbPath);
                    thumbSrc = `${thumbsBase}/${name}.webp`;

                    // Build a responsive srcset from whichever width variants
                    // exist on disk (generated by scripts/optimize-photos.mjs).
                    const candidates = [
                        { w: 400, file: `${name}-400.webp` },
                        { w: 800, file: `${name}.webp` },
                        { w: 1200, file: `${name}-1200.webp` },
                    ];
                    const present: string[] = [];
                    for (const c of candidates) {
                        try {
                            await access(join(photosDir, "thumbs", c.file));
                            present.push(`${thumbsBase}/${c.file} ${c.w}w`);
                        } catch {
                            // variant not generated yet
                        }
                    }
                    if (present.length > 1) thumbSrcset = present.join(", ");
                } catch {
                    // Thumbnail doesn't exist, use original
                }

                return {
                    src: `/images/photography/${filename}`,
                    thumbSrc,
                    thumbSrcset,
                    alt,
                    filename,
                    orientation,
                    width,
                    height,
                    exif,
                };
            })
        );

        // Sort by date (newest first) - photos without dates go to the end
        photos.sort((a, b) => {
            // Both have dates - sort by date descending (newest first)
            if (a.exif.date && b.exif.date) {
                return b.exif.date.localeCompare(a.exif.date);
            }
            // Only a has date - a comes first
            if (a.exif.date && !b.exif.date) {
                return -1;
            }
            // Only b has date - b comes first
            if (!a.exif.date && b.exif.date) {
                return 1;
            }
            // Neither has date - sort by filename
            return a.filename.localeCompare(b.filename);
        });

        return { photos };
    } catch (error) {
        console.error("Error loading photos:", error);
        return { photos: [] };
    }
};
